// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Recipes.Data;
using System;

namespace Recipes.Migrations
{
    [DbContext(typeof(RecipeContext))]
    [Migration("20180228204234_InitialDb")]
    partial class InitialDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Recipes.Data.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("Recipes.Data.Entities.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Course");
                });

            modelBuilder.Entity("Recipes.Data.Entities.Cuisine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Cuisine");
                });

            modelBuilder.Entity("Recipes.Data.Entities.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Ingredient");
                });

            modelBuilder.Entity("Recipes.Data.Entities.IngredientMeasurement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Measurement");

                    b.HasKey("Id");

                    b.ToTable("IngredientMeasurement");
                });

            modelBuilder.Entity("Recipes.Data.Entities.IngredientPreparation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Preparation");

                    b.HasKey("Id");

                    b.ToTable("IngredientPreparation");
                });

            modelBuilder.Entity("Recipes.Data.Entities.Nutrition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Type");

                    b.HasKey("Id");

                    b.ToTable("Nutrition");
                });

            modelBuilder.Entity("Recipes.Data.Entities.NutritionMeasurement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Measurement");

                    b.HasKey("Id");

                    b.ToTable("NutritionMeasurement");
                });

            modelBuilder.Entity("Recipes.Data.Entities.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Portions");

                    b.Property<int?>("RecipeImageId");

                    b.Property<string>("RecipeName");

                    b.Property<int?>("SkillId");

                    b.HasKey("Id");

                    b.HasIndex("RecipeImageId")
                        .IsUnique()
                        .HasFilter("[RecipeImageId] IS NOT NULL");

                    b.HasIndex("SkillId");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("Recipes.Data.Entities.RecipeCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CategoryId");

                    b.Property<int?>("RecipeId");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeCategory");
                });

            modelBuilder.Entity("Recipes.Data.Entities.RecipeCourse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CourseId");

                    b.Property<int?>("RecipeId");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeCourse");
                });

            modelBuilder.Entity("Recipes.Data.Entities.RecipeCuisine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CuisineId");

                    b.Property<int?>("RecipeId");

                    b.HasKey("Id");

                    b.HasIndex("CuisineId");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeCuisine");
                });

            modelBuilder.Entity("Recipes.Data.Entities.RecipeImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Image");

                    b.HasKey("Id");

                    b.ToTable("RecipeImage");
                });

            modelBuilder.Entity("Recipes.Data.Entities.RecipeIngredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("IngredientId");

                    b.Property<int?>("MeasurementId");

                    b.Property<int?>("PreparationId");

                    b.Property<int>("Quantity");

                    b.Property<int?>("RecipeId");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("MeasurementId");

                    b.HasIndex("PreparationId");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeIngredient");
                });

            modelBuilder.Entity("Recipes.Data.Entities.RecipeMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Method");

                    b.Property<int?>("RecipeId");

                    b.Property<int>("StepNumber");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeMethod");
                });

            modelBuilder.Entity("Recipes.Data.Entities.RecipeNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Note");

                    b.Property<int?>("RecipeId");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeNote");
                });

            modelBuilder.Entity("Recipes.Data.Entities.RecipeNutrition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("MeasurementId");

                    b.Property<string>("Quantity");

                    b.Property<int?>("RecipeId");

                    b.Property<int?>("TypeId");

                    b.HasKey("Id");

                    b.HasIndex("MeasurementId");

                    b.HasIndex("RecipeId");

                    b.HasIndex("TypeId");

                    b.ToTable("RecipeNutrition");
                });

            modelBuilder.Entity("Recipes.Data.Entities.RecipeSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Skill");

                    b.HasKey("Id");

                    b.ToTable("RecipeSkill");
                });

            modelBuilder.Entity("Recipes.Data.Entities.RecipeTags", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("RecipeId");

                    b.Property<int?>("TagId");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.HasIndex("TagId");

                    b.ToTable("RecipeTags");
                });

            modelBuilder.Entity("Recipes.Data.Entities.RecipeTimings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("MeasurementId");

                    b.Property<int>("Quantity");

                    b.Property<int?>("RecipeId");

                    b.Property<int?>("TypeId");

                    b.HasKey("Id");

                    b.HasIndex("MeasurementId");

                    b.HasIndex("RecipeId");

                    b.HasIndex("TypeId");

                    b.ToTable("RecipeTimings");
                });

            modelBuilder.Entity("Recipes.Data.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Tag");
                });

            modelBuilder.Entity("Recipes.Data.Entities.TimingMeasurement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Measurement");

                    b.HasKey("Id");

                    b.ToTable("TimingMeasurement");
                });

            modelBuilder.Entity("Recipes.Data.Entities.TimingType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Type");

                    b.HasKey("Id");

                    b.ToTable("TimingType");
                });

            modelBuilder.Entity("Recipes.Data.Entities.Recipe", b =>
                {
                    b.HasOne("Recipes.Data.Entities.RecipeImage", "RecipeImage")
                        .WithOne("Recipe")
                        .HasForeignKey("Recipes.Data.Entities.Recipe", "RecipeImageId");

                    b.HasOne("Recipes.Data.Entities.RecipeSkill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId");
                });

            modelBuilder.Entity("Recipes.Data.Entities.RecipeCategory", b =>
                {
                    b.HasOne("Recipes.Data.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.HasOne("Recipes.Data.Entities.Recipe", "Recipe")
                        .WithMany("Category")
                        .HasForeignKey("RecipeId");
                });

            modelBuilder.Entity("Recipes.Data.Entities.RecipeCourse", b =>
                {
                    b.HasOne("Recipes.Data.Entities.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId");

                    b.HasOne("Recipes.Data.Entities.Recipe", "Recipe")
                        .WithMany("Couse")
                        .HasForeignKey("RecipeId");
                });

            modelBuilder.Entity("Recipes.Data.Entities.RecipeCuisine", b =>
                {
                    b.HasOne("Recipes.Data.Entities.Cuisine", "Cuisine")
                        .WithMany()
                        .HasForeignKey("CuisineId");

                    b.HasOne("Recipes.Data.Entities.Recipe", "Recipe")
                        .WithMany("Cuisine")
                        .HasForeignKey("RecipeId");
                });

            modelBuilder.Entity("Recipes.Data.Entities.RecipeIngredient", b =>
                {
                    b.HasOne("Recipes.Data.Entities.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId");

                    b.HasOne("Recipes.Data.Entities.IngredientMeasurement", "Measurement")
                        .WithMany()
                        .HasForeignKey("MeasurementId");

                    b.HasOne("Recipes.Data.Entities.IngredientPreparation", "Preparation")
                        .WithMany()
                        .HasForeignKey("PreparationId");

                    b.HasOne("Recipes.Data.Entities.Recipe", "Recipe")
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId");
                });

            modelBuilder.Entity("Recipes.Data.Entities.RecipeMethod", b =>
                {
                    b.HasOne("Recipes.Data.Entities.Recipe", "Recipe")
                        .WithMany("Methods")
                        .HasForeignKey("RecipeId");
                });

            modelBuilder.Entity("Recipes.Data.Entities.RecipeNote", b =>
                {
                    b.HasOne("Recipes.Data.Entities.Recipe", "Recipe")
                        .WithMany("Notes")
                        .HasForeignKey("RecipeId");
                });

            modelBuilder.Entity("Recipes.Data.Entities.RecipeNutrition", b =>
                {
                    b.HasOne("Recipes.Data.Entities.NutritionMeasurement", "Measurement")
                        .WithMany()
                        .HasForeignKey("MeasurementId");

                    b.HasOne("Recipes.Data.Entities.Recipe", "Recipe")
                        .WithMany("Nutrition")
                        .HasForeignKey("RecipeId");

                    b.HasOne("Recipes.Data.Entities.Nutrition", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId");
                });

            modelBuilder.Entity("Recipes.Data.Entities.RecipeTags", b =>
                {
                    b.HasOne("Recipes.Data.Entities.Recipe", "Recipe")
                        .WithMany("Tags")
                        .HasForeignKey("RecipeId");

                    b.HasOne("Recipes.Data.Entities.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId");
                });

            modelBuilder.Entity("Recipes.Data.Entities.RecipeTimings", b =>
                {
                    b.HasOne("Recipes.Data.Entities.TimingMeasurement", "Measurement")
                        .WithMany()
                        .HasForeignKey("MeasurementId");

                    b.HasOne("Recipes.Data.Entities.Recipe", "Recipe")
                        .WithMany("Timings")
                        .HasForeignKey("RecipeId");

                    b.HasOne("Recipes.Data.Entities.TimingType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId");
                });
#pragma warning restore 612, 618
        }
    }
}
